import { ModeCard } from "@/src/types/modeCard";

export const MODE_CARDS: ModeCard[] = [
  {
    id: "communication",
    title: "Comunicação",
    subtitle: "Campanhas e conteúdos",
    description: "Gerir formulários, eventos, rewards e notificações com impacto.",
    icon: "bullhorn",
    route: "/(app)/(communication)/dashboard",
    features: ["Formulários", "Eventos", "Rewards", "Notificações"],
    bgColor: "rgba(2,132,199,0.12)",
    borderColor: "border-white/10",
    iconBgColor: "bg-sky-500/20",
    iconBorderColor: "border-sky-400/30",
    iconColor: "#7dd3fc",
    topGlowColor: "bg-sky-400/20",
    bottomGlowColor: "bg-blue-500/20",
  },
  {
    id: "management",
    title: "Gestão",
    subtitle: "Administração interna",
    description: "Controlar utilizadores, permissões e configurações avançadas.",
    icon: "users-cog",
    route: "/(app)/(management)/users",
    features: ["Utilizadores", "Permissões", "Definições"],
    bgColor: "rgba(16,185,129,0.12)",
    borderColor: "border-white/10",
    iconBgColor: "bg-emerald-500/20",
    iconBorderColor: "border-emerald-400/30",
    iconColor: "#34d399",
    topGlowColor: "bg-emerald-400/20",
    bottomGlowColor: "bg-emerald-500/20",
  },
  // {
  //   id: "analytics",
  //   title: "Análise",
  //   subtitle: "Relatórios e insights",
  //   description: "Monitorizar KPI operacionais e exportar relatórios.",
  //   icon: "chart-line",
  //   route: "/(app)/(analytics)/dashboard",
  //   features: ["KPIs", "Relatórios", "Export"],
  //   bgColor: "rgba(139,92,246,0.12)",
  //   borderColor: "border-white/10",
  //   iconBgColor: "bg-purple-500/20",
  //   iconBorderColor: "border-purple-400/30",
  //   iconColor: "#d8b4fe",
  //   topGlowColor: "bg-purple-400/20",
  //   bottomGlowColor: "bg-purple-500/20",
  // },
  // {
  //   id: "operations",
  //   title: "Operações",
  //   subtitle: "Chão de fábrica",
  //   description: "Registar produção, turnos e incidentes críticos.",
  //   icon: "industry",
  //   route: "/(app)/(operations)/dashboard",
  //   features: ["Produção", "Turnos", "Incidentes"],
  //   bgColor: "rgba(245,158,11,0.12)",
  //   borderColor: "border-white/10",
  //   iconBgColor: "bg-amber-500/20",
  //   iconBorderColor: "border-amber-400/30",
  //   iconColor: "#fbbf24",
  //   topGlowColor: "bg-amber-400/20",
  //   bottomGlowColor: "bg-amber-500/20",
  // },
];
